---
title: "0405下"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vectorExample <- c(2,6,7)
listExample <- list(2,6,7)

print(vectorExample)
print(listExample)
```
每個元素值可以是不同type的物件值。
```{r}
c("2020-03-31T13:40:55Z","一芳","2杯","水果茶")
```
用list儲存
```{r}
library(lubridate)
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```
物件值可以是vector形式，也可以list
```{r}
c(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
```
```{r}
# list含兩個vectors
 list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
```
```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```
```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```
```{r}
# list含兩個lists,子層又包含vectors
`小明108學年課表c` <- list(
  `上學期`=list(smester=c("108-1"),
       courses=c("高級會計學","高等統計學")
       ),
  `下學期`=list(smester=c("108-2"),
       courses=c("食在拉丁美洲")
  )
)
print(`小明108學年課表c`)
```
#GitHub commit
```{r}
commit <- list(author=list(name="Martin老師",
                           email="mtlin@gm.ntpu.edu.tw",
                           time=ymd_hms ("2020-03-25T07:17:40Z")),

        committer=list(name="emilyluckey",
                       email="emily007@gmail.com",
                       time=ymd_hms("2020-03-26T08:18:40Z")),
        message = "update")
print(commit)
```
```{r}
browseURL("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") 
```
```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(commit)
```
##practice(me)
```{r}
`小明` <- list(`108學年第一學期`=list(course1=list("Alice老師","個體經濟學",85),course2=list("Mark老師","總體經濟學",73)),
             `108學年第二學期`=list("Jason老師","作業研究",90))
print(`小明`)
```
##practice(teacher)
```{r}
`小明的修課記錄` <- 
  list(
    name="小明",
    semesters=
      list(
        `108-1`=
          list(
            year=108,
            semester=1,
            courses=
              list(
                list(
                  name="個體經濟學",
                  teacher="Alice",
                  grade=85
                ),
                list(
                  name="總體經濟學",
                  teacher="Mark",
                  grade=78
                )
              )
            ),
        `108-2`=
          list(
            year=108,
            semester=2,
            courses=
              list(
                list(
                  name="作業研究",
                  teacher="Jason",
                  grade=90
                )
              )
            )
      ) 
    )
print(`小明的修課記錄`)
```
##json
```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```
##3-7
```{r}
save(commit,listExample,file="0405.Rda")
```

```{r}
load("0405.Rda")
```
##practice2
```{r}
library(lubridate)
weather<-list(
  `台北市`=
    list(date=
           c(ymd("2020-03-31","2020-04-01")),
                         highest=25,
                         lowest=18
),
`新北市`=list(date=
             c(ymd("2020-03-31","2020-04-01")),
                         highest=24,
                         lowest=15)
)
print(weather)

```





```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
