---
title: '0521'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages(c("purrr"))
library(purrr)
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```
```{r}
pick_小新 <- example$name == "小新"
data_selected <- 
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )
```
```{r}
map(example, ~.x[pick_小新]) -> 
  data_selected 
  
data_selected
```
```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
str(dance)
```
```{r}

# 第一個dance表演名稱
dance[[1]]$title
# 第二個dance表演名稱
dance[[2]]$title
```
```{r}

map(dance, ~.x$title) ->
  list_titles

View(list_titles)

```

```{r}
map(dance,~length(.x$showInfo)) ->
  list_numberOfShows 
  
View(list_numberOfShows)
```

```{r}
str(dance[[4]]$showInfo)
```

```{r}
map(dance[[4]]$showInfo, ~ .x$time) ->
  
list_showTimes_dance4
```

```{r}
str(dance[[8]]$showInfo)
map(dance[[8]]$showInfo, ~.x$time)
```
```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/api/datasets/34B402A8-53D9-483D-9406-24A682C2D6DC/json/preview", simplifyDataFrame = F) -> busRoutes
```
```{r}
str(busRoutes)
```
Id(路線代碼)、providerId(業者代碼)、providerName(業者中文名稱)、nameZh(中文名稱)
```{r}
map(busRoutes, ~.x$Id)
map(busRoutes, ~.x$providerId)
map(busRoutes, ~.x$providerName)
map(busRoutes, ~.x$nameZh)

```
```{r}
jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```
```{r}
#2-1
weather_next36hours$cwbopendata$dataset$location$locationName
#2-2
map(weather_next36hours$cwbopendata$dataset$location$weatherElement, ~.x$elementName)

#2-3
map(weather_next36hours$cwbopendata$dataset$location$weatherElement,~.x$time[[1]]$startTime)

map(weather_next36hours$cwbopendata$dataset$location$weatherElement,~.x$time[[1]]$endTime)

map(weather_next36hours$cwbopendata$dataset$location$weatherElement,~max(.x$time[[1]]$parameter[[2]]))
```
```{r}
threeHeigths <- c(Gary=178, John=182, Cam=175)
```
```{r}
#第一個寫法
# 先排序由大到小，
sort(threeHeigths, decreasing=T) -> sorted_heights
sorted_heights

# 把排好的人名取出
names(sorted_heights) -> sorted_persons

# 接著取出第一個位置的人名
sorted_persons[[1]] -> highestPerson

#寫法二 
names(sort(threeHeigths, decreasing = T))[[1]] -> highestPerson
```
```{r}
library(magrittr)
sort(threeHeigths, decreasing=T) %>% 
names(.) %>%
.[[1]] -> highestPerson
```
```{r}
f(w) -> x
g(x) -> y
h(y) -> z
```
```{r}
f(w) %>%
  g(.) %>% 
  h(.) -> z

w %>%
  f(.) %>%
  g(.) %>%
  h(.) -> z
```
```{r}
# 由cities創出每個元素對應的北部、東部、中部region factor
cities <- factor(c("台北","花蓮","台東","台中"))
levels(cities)
```
```{r}
region <- cities

# 以下為一連串的pipe operation
levels(region) -> currentLevels
str_replace(currentLevels,"台北","北部") -> currentLevels1
str_replace(currentLevels1,"花蓮|台東","東部") -> currentLevels2
str_replace(currentLevels2,"台中","中部") -> regionLevels
regionLevels -> levels(region)
```
```{r}
levels(region) %>% 
  str_replace(.,"台北","北部") %>%
  str_replace(.,"花蓮|台東","東部") %>%
  str_replace(.,"台中","中部") ->
  levels(region)
```
```{r}
num <- c(2,97,22,15,7)

# 選出大於50的數字
(num > 50) -> pick_big
num[pick_big]
```
```{r}
(num > 50) %>%
  num[.]
```
```{r}
threeHeights %>%
  .sort(., decreasing=T) %>%
  names(.) %>%
  .[[1]] -> highestPerson
```
```{r}
# 資料
population <- c(`cityA`=500,`cityB`=1500, `cityC`=399)
cities <- c("cityA","cityA","cityB","cityB","cityC")

# 分析步驟
names(sort(population)) -> setLevels
factor(cities, levels = setLevels) -> cities 
```
```{r}
population %>%
  sort() %>%
  names() %>%
  factor(cities, levels=.) -> cities
```

```{r}
dataList <- list(
  num=c(2,97,22,15,7),
  chr=c("2","97","22","15","7")
)
```
```{r}
map(dataList, is.numeric) -> results
map(dataList,~is.numeric(x))
results
unlist(results) -> pick_numeric
class(pick_numeric)
dataList[pick_numeric] -> num_element
class(num_element)
(num_element[[1]] > 50) -> pick_big
num_element[[1]][pick_big] -> bigNumber
```


```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
