---
title: "0625"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
n<- 540

conditionExpression_outcome=
  ifelse(n %% 2==0, "even", "odd") 

switch(
  conditionExpression_outcome,
  "even"={fvalue <- n/2}, # 偶數
  "odd"=fvalue <- -(n+1)/2, # 奇數；只有一行指令可省略{}
  warning("n要整數喔")  
)

print(fvalue)
```
```{r}
myFun <- function(x,y){
  return(x**y+15)
}

# 等同於
myFun2 <- function(x,y){
  x**y+15
}

myFun(5,3) -> outcome
myFun2(5,3) -> outcome2
print(outcome)
print(outcome2)

```

```{r}
grade <- sample(1:100, 10, replace=T)

  cut(grade,c(-1,69,79,89,100)) -> grade

levels(grade)

switch(
  as.character(grade[[1]]),
  "(-1,69]"={
    print("-_-")
    "F"},
  "(69,79]"={
    "棒"
    "C"
    },
  "(79,89]"={
   "好棒"
    "B"
    },
  "(89,100]"={
    "好棒棒"
    "A"
    }
) -> letterGrade # 有回存時要螢幕印出的訊息一定要加print
```

```{r}
nowtime <- glue::glue("{today()} 18:00:00") %>% ymd_hms(tz="Asia/Taipei")

library(lubridate)
library(glue)

# 建立可當cutpoints的一天時間點
cutpoints <-
  c(
    glue("{today()} 06:00:00"),
    glue("{today()} 09:00:00"),
    glue("{today()} 17:00:00"),
    glue("{today()} 19:00:00"),
    glue("{today()} 23:30:00"),
    glue("{today()+days(1)} 01:00:00")
  )
cutpoints %>%
  ymd_hms(tz="Asia/Taipei") -> cutpoints

## 將nowtime轉成它對應的時段是"morning", "evening", 或其他。
cut(nowtime, cutpoints) -> nowtime
nowtime
levels(nowtime)[c(1,3,5)] <-
  c("morning","evening","jazz time")
levels(nowtime)

## 使用switch決定要做什麼事
dplyr::case_when(nowtime=="morning" ~print("要不要來閱讀點國際時事？")
    browseURL("https://economist.com") ,
    nowtime=="evening" ~print("需不需要點餐呢？")
    browseURL("https://www.foodpanda.com.tw/"),
    nowtime=="jazz time" ~print("放鬆聽點Jazz。")
    browseURL("https://open.spotify.com/playlist/37i9dQZF1DXbITWG1ZJKYt"))
  
 
    print("機器人要休息，饒了我吧～～")
  

```
```{r}

```



```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
