---
title: "review"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
my_108_total_credits <- 15
my.108.total_credits <- 15
.my.108.total_credits <- 15
`我的108學年總學分數` <- 15 
`.108.total_credits` <- 15
```
```{r}
`我的年紀` <- 20
myAge <- `我的年紀`
```
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

majors10_factor
majors10_char

```
```{r}
as.integer(majors10_factor) 
```
```{r}
studentId <- c(410773002, 410773015)
charStudent <- as.character(studentId)
charStudent
```
##台北 2020-03-18 13:52:40
  葡萄牙 Mar.18, 2020, 05:52:40

```{r}
library(lubridate)
TpeTime <- ymd_hms("2020-03-18 13:52:40",tz="Asia/Taipei")
PTime <- mdy_hms("Mar.18, 2020, 05:52:40",tz="Europe/Lisbon")

```
```{r}
twoTimes <- c(ymd_hms(TpeTime,tz="Asia/Taipei"),ymd_hms(PTime,tz="Europe/Lisbon"))
with_tz(twoTimes,tz="UTC") -> twoTimes
twoTimes
```
```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
     tz="Asia/Taipei")
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
```
```{r}
class(tpeTime)
typeof(tpeTime)

as.numeric(tpeTime)
as.numeric(pgTime)
```
```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
`小明108學年課表A`
```
```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
names(listExample)
listExample$`學期`
```
```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]
str(get1)
str(get2)
```
```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")
```
```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")

econOnly <- c(1,2,5)
names[econOnly]
gender[econOnly]
econFemaleOnly <-gender[econOnly][c(T,T,F)]
names[econOnly][c(T,T,F)]
```
```{r}
today <- list(
  list("台北市",highest_temp = 25,lowest_temp = 18),
  list("新北市",highest_temp = 24,lowest_temp = 15))
tomorrow <- list(
  list("台北市",highest_temp = 25,lowest_temp = 18),
  list("新北市",highest_temp = 24,lowest_temp = 15))

weather <- list(today,tomorrow)

print(weather)
```
```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```
```{r}
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```
```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21)

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```






```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
